### ISSUE TITLE
How are custom environment variables implemented?

### ISSUE THREAD

**Issue by ben-z** [OSC/ood-documentation#1000]
Hi! I was reading your documentation on the available [environment variables](https://www.osc.edu/supercomputing/batch-processing-at-osc/slurm_migration/how_to_prepare_slurm_job_scripts) and how you [use `SLURM_JOB_GRES` in the SLURM prolog](https://osc.github.io/ood-documentation/latest/installation/resource-manager/advanced-configs.html). I'm wondering how you managed to make `SLURM_JOB_GRES` accessible in the prolog? I'm trying to do something similar for a cluster at my school (https://cloud.watonomous.ca/) and I'm currently using `scontrol` to get this information in the prolog. However, `scontrol` sometimes takes more than 10 seconds and results in a job initialization failure (`run_command_poll_child: initscript poll timeout @ 10000 msec`).

**Comment by johrstrom** [comment]
>  I'm wondering how you managed to make SLURM_JOB_GRES accessible in the prolog?

I'm pretty sure Slurm just populates them correctly when (a) it's been configured correctly and (b) the job in question has been allocated that gres.

**Comment by ben-z** [comment]
Thanks! Though in the vanilla SLURM setup I'm running, the variable doesn't appear anywhere. I did a bit more digging and it seems that OSC is using a custom fork of SLURM with `SLURM_JOB_GRES` injected by a SPANK plugin:
- https://discourse.openondemand.org/t/virtualgl-in-ood-apps/750/7
- https://github.com/treydock/slurm/commit/a4ec8b31784a79ce806c175ff9b9c8bed18b1df4

**Comment by johrstrom** [comment]
🤦‍♂️ you're a better detective than I am. @treydock is this still the case - that we have to fork & update the spank plugin to get GRES environment variables in a Slurm prologue?

**Comment by treydock** [comment]
Unfortunately SLURM_JOB_GRES is still a custom plugin we inject into the Slurm source code before we build Slurm RPMs.  

We inject the environment variable using a job submit plugin: https://github.com/SchedMD/slurm/commit/636c891290e049b2a8b22b1a5a9b43ae2ca4ff30

Just be sure to set `gres_env` after `lua` ie:

```
JobSubmitPlugins=lua,gres_env
```

I don't recall why we don't do this in Lua.  I think it has to do with needing to set the SPANK variable too which can't do from Lua job submit plugin.

We also have SPANK plugin here: https://github.com/SchedMD/slurm/commit/a4ec8b31784a79ce806c175ff9b9c8bed18b1df4

I think that the SPANK plugin is what makes the variable show up inside the Prolog.  It's been years since I wrote all this so I maybe forgetting how it's all tied together.

Not sure why Github shows the repo as SchedMD, but got commits from here comparing my fork from SchedMD: https://github.com/SchedMD/slurm/compare/master...treydock:slurm:osc-slurm-23-11-5-1

If you don't want to deal with custom plugins, there is `SLURM_JOB_EXTRA` environment variable that Slurm will add to the Prolog environment, so rather than using a GRES to trigger Visualization jobs you could have some documented value to the `--extra` flag to sbatch.

**Comment by ben-z** [comment]
Ah got it. Thanks for the information and the note about `SLURM_JOB_EXTRA`--didn't know about that variable before. I think this ticket is very well answered now and I'll close it. For my use case I'll discuss with my team about whether to use `SLURM_JOB_EXTRA` or custom plugins.
