### ISSUE TITLE
Development Workflow

### ISSUE THREAD

**Issue by vsoch** [OSC/ood-documentation#177]
Hi! I'd like to work on developing OnDemand apps, and I'm looking for a local development environment (Docker containers?) that I might be able to easily bring up to jump into either of the interactive app tutorials. Does this exist?

**Comment by johrstrom** [comment]
Hit there! 

1. Awesome name!
2. There's an up to date [Docker file in this repo](https://github.com/OSC/ood-images).
3. That said, you don't actually need to develop apps locally. You should be able to develop against your production instance in your local home directory. Your administrators could have setup the dashboard (what you login to and use) as described [here](https://osc.github.io/ood-documentation/master/app-development/enabling-development-mode.html).  So for me at my institution (OSC) I'm able to develop apps right in my `~/ondemand/dev` directory. These apps only show up for me but they're launched through the production OSC dashboard. 

I hope that helps. There are some [tutorials here](https://osc.github.io/ood-documentation/master/app-development/tutorials-interactive-apps.html) if you need them.

**Comment by ericfranz** [comment]
@vsoch we do not have exactly what you are looking for.

The ood-images repo @johrstrom shared has an OnDemand instance but that is not configured to submit jobs. This repo https://github.com/osc/ood-images-full has a Vagrant image with OnDemand and Slurm installed and can be used for testing job submission, and thus theoretically, interactive apps. However, none of the setup required to support interactive apps, such as the Apache configuration to enable the interactive app proxy or installation of the software itself, such as Jupyter or RStudio. Also, the Vagrant image takes a good hour or so to install, since it builds Slurm from source.

If the Vagrant image will work I can provide help with setup.

Otherwise, do you think it would be feasible for us to install OnDemand and a batch scheduler and Jupyter notebook server in the same image?

FWIW I think this work will be much easier at the end of this year or early next: hopefully by then we will have a fork adapter as an alternative to batch schedulers for OnDemand, a lighter OnDemand install, and a simpler plugin format for interactive apps.

**Comment by vsoch** [comment]
@johrstrom and @ericfranz thanks for the speedy response! I’m going to test these out soon and will post back with an update. If it’s ok with you, I’d like to leave the issue open in case there is more to discuss. Happy Sunday!

**Comment by vsoch** [comment]
okay, starting work on this today.

**Comment by ericfranz** [comment]
@vsoch I wrote (hopefully) clearer instructions on enabling developer mode but somehow Travis failed to build the docs after merging into the develop branch of the documentation. There is, however, a build on the test site that has it: https://osc.github.io/ood-documentation-test/fix_dev_enabling_docs/app-development/enabling-development-mode.html

**Comment by vsoch** [comment]
No worries, I'm actually trying something new because I want to use Docker containers (via docker-compose) instead. I'm going to fuss around and break things for a while, and I'll poke back when I need help :) Thank you!

**Comment by vsoch** [comment]
Woo! Just got the very basics working with ood, slurm, and docker-compose:

![image](https://user-images.githubusercontent.com/814322/60117924-2aeb9600-9749-11e9-9336-1543beb8f810.png)

There were a lot of hassles with centos:7 and systemctl, and then I still need to debug the hostname, but this is great progress for the morning! SLURM and the very basic portal are brought up, but of course I'm sure there are many more eggs to fry. I'm going to take a break and be back working in a bit.

**Comment by ericfranz** [comment]
Oh wow amazing!

**Comment by vsoch** [comment]
Okay I got them talking to one another (at least for job submission)

![image](https://user-images.githubusercontent.com/814322/60122562-786d0080-9753-11e9-8582-58fc9b11fad1.png)

**Comment by vsoch** [comment]
okay I have the basics working -> https://github.com/vsoch/ood-compose

Do you guys have ideas for where the apache configuration is (to set the hostname) and then how to best allow ssh from the interface? (See the issues board, I created an issue for each so you can comment directly!)

**Comment by ericfranz** [comment]
Looking into the ssh issue. For interactive apps you will need to configure the rnode and node proxies - this is again an ood-portal.yml modification. https://osc.github.io/ood-documentation/master/app-development/interactive/setup/enable-reverse-proxy.html

**Comment by vsoch** [comment]
Thanks for all of your help! I have the slurm + docker-compose + interactive nodes all working.
https://github.com/vsoch/ood-compose

The browser-based ssh still has a bug, but I'm able to easily develop apps (example rstudio is provided) which was my goal. If you think it would be useful to others, would you be interested in having it hosted by OSC? I'd be glad to be a maintainer on the repo. Otherwise, if it's useful (but doesn't need to be a part of OSC) I could offer to PR somewhere to add it to docs. Either way, thank you kindly for the help! I am happy to close the issue.
