### ISSUE TITLE
Dashboard not showing all apps for user

### ISSUE THREAD

**Issue by bgillpgh** [OSC/ood-documentation#839]
Older Ondemand install (1.8.2) that for one particular user fails to show all the dashboard apps. It shows Rstudio, then there should be an entry for Jupyter notebook but that never loads. I'm just trying to understand what it's trying to do when it loads the apps that could possibly be different between one user and another, any ideas? To be clear, for every other user the normal list of apps loads just fine, even another user who logged in on the broken user's browser.

**Comment by johrstrom** [comment]
I would check the file permissions of those applications. A quick read of this suggests that they cannot read the directory for jupyter.

**Comment by bgillpgh** [comment]
I can't find any difference in permissions between the apps, both are
readable by everyone and users have uniform privileges on this machine. I
suspect that something in the user's environment is being read when the
jupyter app is loading, like a python startup file or something but I can't
find any obvious candidates.

**Comment by johrstrom** [comment]
> I suspect that something in the user's environment is being read 

OnDemand (the web app portion) does not read the users environment. That is, it doesn't read/execute a `~/.bashrc` or anything like that. (the jobs the web app will submit start SHELL environments, but that's during the jobs execution, not within the per user nginx - PUN).  The environments should be uniform across all user PUNs.

What's not uniform across all user PUNs are the UID and GID(s) the application boots up with. The web application will search all the directories in `/var/www/ood/apps/sys/` if it's a system installed application. If it can read the children directories here then every directory will become an 'app'.  This is why I'm wondering about file permissions. 

File permissions are the primary mechanism we use to hide or disable applications.
I'd ask these other questions:
* Is Jupyter a system installed application or is it being shared from someone? If it's being shared, check those permissions.
* double check for any FACLs that may be applied to Jupyter. You may see that it's 755 readable, but somehow there's a FACL that disables it for this user.
* There's an edge case here where the Jupyter application is using a cluster the user can't see. And so, we're not showing the app because the user can't see the cluster it uses. Check the `cluster.d` files for the cluster this app users. Check to see if this user can read _those cluster_ files as well.
  *  These cluster files also provide a mechanism to enable and disable users through groups. Check to see if these cluster.d files have an `acl` configurations that could be blocking this user.

**Comment by johrstrom** [comment]
This does not seem to be a documentation ticket, so I'm closing it now.  Should you continue to have issues, I can reopen or you can open a topic on our discourse instance: https://discourse.openondemand.org/
