### ISSUE TITLE
11. LDAP support

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-documentation#9]
The ldap URI for osc does not work correctly.

Updating to:

```
  - 'AuthLDAPURL "ldap://cts06.osc.edu/ou=People,ou=hpc,o=osc?uid"'
```

fixed the issue.

**Comment by ericfranz** [comment]
>  - 'AuthLDAPURL "ldaps://cts06.osc.edu:636/ou=People,ou=hpc,o=osc?uid" SSL'

We ideally want to be using SSL when connecting to the LDAP server. I don't know why you couldn't use SSL when you were walking through the installation. Extra steps perhaps that are out side the scope of the OOD installation directions?

**Comment by brianmcmichael** [comment]
I think the webdev07 server needs to be whitelisted on cts06 for ssl to work.

**Comment by nickjer** [comment]
This probably needs a ticket opened with Trey to enable support for this in all future blank OOD VM installs.

**Comment by treydock** [comment]
So everyone is aware, the current LDAP servers use an internal CA to sign their certs.  This CA is not trusted by the system and uses MD5 cert which is actually untrusted regardless of CA on RHEL7 systems.  There are hacks to support MD5 but they are ugly.  The new LDAP servers have SHA256 certs and are trusted by the OS CA cert bundle.  These new LDAP servers will be going live sometime between now and May 23rd.

If it helps WIAG make better documentation, you all can use openldap[1-4].infra.osc.edu as LDAP servers.  The schema is the same but the SSL support is much better.  No guarantees on stability as those hosts are not yet production and I have to periodically purge LDAP to re-sync with the production LDAP master.

I'd recommend either using SSL (port 636) or TLS (port 389).  The TLS usually has to be enabled since it uses same port as unencrypted LDAP.

**Comment by nickjer** [comment]
I am fine with changing the documentation to point to `ldaps://openldap1.infra.osc.edu:636...`. We need to first test with on `webdev07`.

**Comment by nickjer** [comment]
Updated in e3f71860d92e56a45ad54e54bb217ec1f9273fab
